"use client"
import Image from 'next/image'
import Header from '@/components/header'
import { useEffect, useState } from 'react';

interface ArticleData {
    headline: string;
    body: string;
    image_url: string;
}

export default function Article({ params }: { params: { id: string } }) {

    const [article, setArticle] = useState<ArticleData | null>(null);

    useEffect(() => {
        async function fetchArticle() {
            try {
                const res = await fetch(`/api?id=${params.id}`);
                const data = await res.json();
                setArticle(data);
            } catch (error) {
                console.error("Failed to load article", error);
                setArticle(null);
            }
        }

        fetchArticle();
    }, [params.id]);

    console.log(article?.image_url)

    return (
        <>
            <Header />
            {article ? (
                <div className="px-4 py-6 md:px-6 md:py-12 lg:py-16">
                    <article className="prose prose-zinc mx-auto dark:prose-invert max-w-xl">
                        <div className="space-y-2 not-prose">
                            <h1 className="text-3xl font-extrabold tracking-tight lg:text-4xl lg:leading-[3.5rem] text-center">
                                {article.headline}
                            </h1>
                            <p className="text-zinc-500 dark:text-zinc-400">Posted on November 13, 2023</p>
                        </div>
                        <Image
                            alt="Breaking news image"
                            className="aspect-content overflow-hidden rounded-lg object-cover"
                            height={400}
                            src={article.image_url}
                            width={1200}
                        />
                        <br />
                        <p>
                            {article.body}
                        </p>
                        <br />
                        <p>
                            Please note: The content presented in the article above is entirely generated by artificial intelligence and should not be considered real or factual. It is a product of AI technology, designed for illustrative or creative purposes only, and does not represent actual events, people, or entities. Caution should be exercised in interpreting this AI-generated content, as it is purely fictional and intended for demonstration purposes.
                        </p>
                    </article>
                </div>
            ) : (
                <p>Loading article...</p>
            )}
        </>
    );
}